name: run-test

on:
  push:
    branches: [dev, master]
  pull_request:
    branches: [dev, master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
        # Install pip and pytest
      - name: Install dependencies
        run: |
          pip install .
      - name: Install xpore-package
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-dependency
      - name: Test with pytest
        run: pytest --junitxml=junit/test-results-${{ matrix.python-version }}.xml
      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
